// AUTO-GENERATED by scripts/build-data.ts — DO NOT EDIT
// Generated: 2026-03-09T04:19:28.326Z

import type { Datasheet, FactionRulesData, FactionId, GeneralRulesDocument } from '../types';

export { UNITS } from './units';
export { FACTION_RULES } from './rules';
export { CORE_RULES, CRUSADE_RULES, RULES_COMMENTARY } from './general';

import { UNITS } from './units';
import { FACTION_RULES } from './rules';

// --- Helper functions ---

export function getUnitsForFaction(factionId: FactionId): Datasheet[] {
  return UNITS[factionId] ?? [];
}

export function getRulesForFaction(factionId: FactionId): FactionRulesData | undefined {
  return FACTION_RULES[factionId];
}

export function getAllFactionSlugs(): FactionId[] {
  return Object.keys(UNITS) as FactionId[];
}

export function searchUnits(query: string, factionId?: FactionId): Datasheet[] {
  const q = query.toLowerCase().trim();
  if (!q) return factionId ? getUnitsForFaction(factionId) : getAllUnits();
  const pool = factionId ? getUnitsForFaction(factionId) : getAllUnits();
  return pool.filter(
    (u) =>
      u.name.toLowerCase().includes(q) ||
      u.keywords.some((k) => k.toLowerCase().includes(q))
  );
}

export function getAllUnits(): Datasheet[] {
  const all: Datasheet[] = [];
  for (const factionId of getAllFactionSlugs()) {
    all.push(...getUnitsForFaction(factionId));
  }
  return all;
}
